---
- name: monstaftp | find existing installation
  stat:
    path: /usr/share/monstaftp/mftp
  register: monstaftp_installation

- name: monstaftp | ensure /usr/share/monstaftp
  file:
    dest: /usr/share/monstaftp
    state: directory
    owner: www-data
    group: www-data

- name: monstaftp | Extracting Monstaftp
  unarchive:
    src: "{{ monstaftp_file_src }}"
    dest: /usr/share/monstaftp
    owner: www-data
    group: www-data
  when: monstaftp_installation.isdir is not defined

- name: monstaftp | settings | config.php
  template:
    src: templates/usr/share/monstaftp/mftp/settings/config.php.j2
    dest: "/usr/share/monstaftp/mftp/settings/config.php"
    owner: www-data
    group: www-data
    mode: "0644"

- name: monstaftp | license | config_pro.php
  template:
    src: templates/usr/share/monstaftp/mftp/license/config_pro.php.j2
    dest: "/usr/share/monstaftp/mftp/license/config_pro.php"
    owner: www-data
    group: www-data
    mode: "0644"
  when:
    - monstaftp_configPathLicense is defined
    - monstaftp_configPathProfiles is defined
